// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// RecordHandler is an autogenerated mock type for the RecordHandler type
type RecordHandler struct {
	mock.Mock
}

// CreateRecordAPI provides a mock function with given fields: ctx
func (_m *RecordHandler) CreateRecordAPI(ctx *gin.Context) {
	_m.Called(ctx)
}

// DeleteRecordAPI provides a mock function with given fields: ctx
func (_m *RecordHandler) DeleteRecordAPI(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetRecordAPI provides a mock function with given fields: ctx
func (_m *RecordHandler) GetRecordAPI(ctx *gin.Context) {
	_m.Called(ctx)
}

// ListRecordsAPI provides a mock function with given fields: ctx
func (_m *RecordHandler) ListRecordsAPI(ctx *gin.Context) {
	_m.Called(ctx)
}

// UpdateRecordAPI provides a mock function with given fields: ctx
func (_m *RecordHandler) UpdateRecordAPI(ctx *gin.Context) {
	_m.Called(ctx)
}
