apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullname" . }}-dns
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dnsService.type }}
  ports:
    - port: {{ .Values.dnsService.port }}
      targetPort: dns
      protocol: UDP
      name: dns
  selector:
    {{- include "charts.selectorLabels" . | nindent 4 }}
