apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullname" . }}-http
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.httpService.type }}
  ports:
    - port: {{ .Values.httpService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "charts.selectorLabels" . | nindent 4 }}
