// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/record": {
            "get": {
                "description": "Get dns record by name, qtype, qclass",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Domain Name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Record Type",
                        "name": "qtype",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Record Class",
                        "name": "qclass",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cewuandy_go-restful-dns_internal_domain.A"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cewuandy_go-restful-dns_internal_domain.Error"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete dns record by name, qtype, qclass",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "parameters": [
                    {
                        "description": "The example of Question request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dns.Question"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cewuandy_go-restful-dns_internal_domain.A"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cewuandy_go-restful-dns_internal_domain.Error"
                        }
                    }
                }
            }
        },
        "/record/{recordType}": {
            "put": {
                "description": "Update an existed dns record",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "parameters": [
                    {
                        "description": "The example of A record request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_cewuandy_go-restful-dns_internal_domain.A"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_cewuandy_go-restful-dns_internal_domain.A"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cewuandy_go-restful-dns_internal_domain.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new dns record",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "parameters": [
                    {
                        "description": "The example of A record request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_cewuandy_go-restful-dns_internal_domain.A"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_cewuandy_go-restful-dns_internal_domain.A"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cewuandy_go-restful-dns_internal_domain.Error"
                        }
                    }
                }
            }
        },
        "/records": {
            "get": {
                "description": "List all dns record",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_cewuandy_go-restful-dns_internal_domain.A"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_cewuandy_go-restful-dns_internal_domain.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dns.Question": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "\"cdomain-name\" specifies encoding (and may be compressed)",
                    "type": "string"
                },
                "qclass": {
                    "type": "integer"
                },
                "qtype": {
                    "type": "integer"
                }
            }
        },
        "github_com_cewuandy_go-restful-dns_internal_domain.A": {
            "type": "object",
            "required": [
                "a",
                "hdr"
            ],
            "properties": {
                "a": {
                    "description": "should be like \"192.168.0.1\"",
                    "type": "string"
                },
                "hdr": {
                    "$ref": "#/definitions/github_com_cewuandy_go-restful-dns_internal_domain.RR_Header"
                }
            }
        },
        "github_com_cewuandy_go-restful-dns_internal_domain.Class": {
            "type": "string",
            "enum": [
                "INET",
                "CSNET",
                "CHAOS",
                "HESIOD",
                "NONE",
                "ANY"
            ],
            "x-enum-varnames": [
                "ClassINET",
                "ClassCSNET",
                "ClassCHAOS",
                "ClassHESIOD",
                "ClassNONE",
                "ClassANY"
            ]
        },
        "github_com_cewuandy_go-restful-dns_internal_domain.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "github_com_cewuandy_go-restful-dns_internal_domain.RRType": {
            "type": "string",
            "enum": [
                "None",
                "A",
                "NS",
                "MD",
                "MF",
                "CNAME",
                "SOA",
                "MB",
                "MG",
                "MR",
                "NULL",
                "PTR",
                "HINFO",
                "MINFO",
                "MX",
                "TXT",
                "RP",
                "AFSDB",
                "X25",
                "ISDN",
                "RT",
                "NSAPPTR",
                "SIG",
                "KEY",
                "PX",
                "GPOS",
                "AAAA",
                "LOC",
                "NXT",
                "EID",
                "NIMLOC",
                "SRV",
                "ATMA",
                "NAPTR",
                "KX",
                "CERT",
                "DNAME",
                "OPT",
                "APL",
                "DS",
                "SSHFP",
                "IPSECKEY",
                "RRSIG",
                "NSEC",
                "DNSKEY",
                "DHCID",
                "NSEC3",
                "NSEC3PARAM",
                "TLSA",
                "SMIMEA",
                "HIP",
                "NINFO",
                "RKEY",
                "TALINK",
                "CDS",
                "CDNSKEY",
                "OPENPGPKEY",
                "CSYNC",
                "ZONEMD",
                "SVCB",
                "HTTPS",
                "SPF",
                "UINFO",
                "UID",
                "GID",
                "UNSPEC",
                "NID",
                "L32",
                "L64",
                "LP",
                "EUI48",
                "EUI64",
                "NXNAME",
                "URI",
                "CAA",
                "AVC",
                "AMTRELAY",
                "TKEY",
                "TSIG",
                "IXFR",
                "AXFR",
                "MAILB",
                "MAILA",
                "ANY",
                "TA",
                "DLV",
                "Reserved"
            ],
            "x-enum-varnames": [
                "TypeNone",
                "TypeA",
                "TypeNS",
                "TypeMD",
                "TypeMF",
                "TypeCNAME",
                "TypeSOA",
                "TypeMB",
                "TypeMG",
                "TypeMR",
                "TypeNULL",
                "TypePTR",
                "TypeHINFO",
                "TypeMINFO",
                "TypeMX",
                "TypeTXT",
                "TypeRP",
                "TypeAFSDB",
                "TypeX25",
                "TypeISDN",
                "TypeRT",
                "TypeNSAPPTR",
                "TypeSIG",
                "TypeKEY",
                "TypePX",
                "TypeGPOS",
                "TypeAAAA",
                "TypeLOC",
                "TypeNXT",
                "TypeEID",
                "TypeNIMLOC",
                "TypeSRV",
                "TypeATMA",
                "TypeNAPTR",
                "TypeKX",
                "TypeCERT",
                "TypeDNAME",
                "TypeOPT",
                "TypeAPL",
                "TypeDS",
                "TypeSSHFP",
                "TypeIPSECKEY",
                "TypeRRSIG",
                "TypeNSEC",
                "TypeDNSKEY",
                "TypeDHCID",
                "TypeNSEC3",
                "TypeNSEC3PARAM",
                "TypeTLSA",
                "TypeSMIMEA",
                "TypeHIP",
                "TypeNINFO",
                "TypeRKEY",
                "TypeTALINK",
                "TypeCDS",
                "TypeCDNSKEY",
                "TypeOPENPGPKEY",
                "TypeCSYNC",
                "TypeZONEMD",
                "TypeSVCB",
                "TypeHTTPS",
                "TypeSPF",
                "TypeUINFO",
                "TypeUID",
                "TypeGID",
                "TypeUNSPEC",
                "TypeNID",
                "TypeL32",
                "TypeL64",
                "TypeLP",
                "TypeEUI48",
                "TypeEUI64",
                "TypeNXNAME",
                "TypeURI",
                "TypeCAA",
                "TypeAVC",
                "TypeAMTRELAY",
                "TypeTKEY",
                "TypeTSIG",
                "TypeIXFR",
                "TypeAXFR",
                "TypeMAILB",
                "TypeMAILA",
                "TypeANY",
                "TypeTA",
                "TypeDLV",
                "TypeReserved"
            ]
        },
        "github_com_cewuandy_go-restful-dns_internal_domain.RR_Header": {
            "type": "object",
            "required": [
                "class",
                "name",
                "rrtype",
                "ttl"
            ],
            "properties": {
                "class": {
                    "$ref": "#/definitions/github_com_cewuandy_go-restful-dns_internal_domain.Class"
                },
                "name": {
                    "type": "string"
                },
                "rdlength": {
                    "type": "integer"
                },
                "rrtype": {
                    "$ref": "#/definitions/github_com_cewuandy_go-restful-dns_internal_domain.RRType"
                },
                "ttl": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "go-restful-dns API",
	Description:      "Documentation of go-restful-dns API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
